
name: C - CI


on:
  push:
    branches: [ Final_Work ]
  pull_request:
    branches: [ Final_Work ]


jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Packages'
      run: |
         sudo apt update
         sudo apt install libcunit1-dev
         sudo apt install libsdl2-dev
         sudo apt install doxygen
    - name: 'Compile'
      run: |
        mkdir BuildCI
        cd BuildCI
        cmake ..
        cmake --build .
    - uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: BuildCI/
  test_linux:
    needs: [build_linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: binaries
          path: BuildCI/
      - name: 'Packages'
        run: |
          sudo apt update
          sudo apt install libcunit1-dev
          sudo apt install libsdl2-dev
          sudo apt install doxygen
      - name: 'Testing'
        run: |
          cd BuildCI
          chmod +x *
          ctest -V
  cover_linux:
    needs: [test_linux]
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/download-artifact@v1
       with:
        name: binaries
        path: BuildCI/
     - name: 'Packages'
       run: |
        sudo apt update
        sudo apt install libcunit1-dev gcovr libcunit1-dev
     - name: 'Coverage'
       run: |
           cd BuildCI
           chmod +x *
           make cover_html
     - uses: actions/upload-artifact@v1
       with:
         name: binaries
         path: BuildCI/      
    
      
    

    
